In [15]:
from transformers import BertForSequenceClassification

In [16]:
import pandas as pd

df = pd.read_csv("../[USETHIS] Experiment Folder/data/dataset_exploded_with_metadata.csv")
df

,Unnamed: 0,text,topic,is_noise_or_spam_text,toxicity,polarized,profanity_obscenity,threat_incitement_to_violence,insults,identity_attack,...,ethnicity,religion,disability,lgbt,gender,age,domisili,pendidikan terakhir,status pekerjaan,president vote leaning
0,0,Wajah Jurnalis Dibalut Perban Saat Melaporkan ...,UNKNOWN,0,0,0,0,0,0,0,...,Minang,Islam,yes,no,F,27,Padang,Sarjana (S1),Bekerja,1
1,1,Wajah Jurnalis Dibalut Perban Saat Melaporkan ...,UNKNOWN,0,0,0,0,0,0,0,...,Tionghoa,Katolik,yes,no,F,21,Jakarta,Sekolah Menengah Atas (SMA),Pelajar/Mahasiswa,3
2,2,Elektabilitas Paslon 02 sebentar lagi terjun b...,Disabilitas,0,0,1,0,0,0,0,...,Minang,Islam,yes,no,F,27,Padang,Sarjana (S1),Bekerja,1
3,3,Elektabilitas Paslon 02 sebentar lagi terjun b...,Disabilitas,0,0,1,0,0,0,0,...,Tionghoa,Katolik,yes,no,F,21,Jakarta,Sekolah Menengah Atas (SMA),Pelajar/Mahasiswa,3
4,4,Gini aja deh @KPU_ID usul aja nih. Gimana kalo...,Disabilitas,0,1,0,0,0,1,0,...,Minang,Islam,yes,no,F,27,Padang,Sarjana (S1),Bekerja,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51965,51965,@pippsstudy abis packing nnt ingfokan cowo kri...,Kristen,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51966,51966,Akun WhatsApp Pj Bupati Tegal Agustyarsah,UNKNOWN,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51967,51967,Buldoser Israel Menabrak Pengungsi Pasien Ruma...,"Jewish, Rohingya",0,0,1,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51968,51968,Perayaan Chinese New Year tahun ini ya akan ma...,Tionghoa,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51969,51969,KNRP #GazaUnderAttack BREAKING NEWS Jumlah Kor...,Jewish,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2

In [17]:
df = df.drop(columns=["Unnamed: 0"])
df

,text,topic,is_noise_or_spam_text,toxicity,polarized,profanity_obscenity,threat_incitement_to_violence,insults,identity_attack,sexually_explicit,...,ethnicity,religion,disability,lgbt,gender,age,domisili,pendidikan terakhir,status pekerjaan,president vote leaning
0,Wajah Jurnalis Dibalut Perban Saat Melaporkan ...,UNKNOWN,0,0,0,0,0,0,0,0,...,Minang,Islam,yes,no,F,27,Padang,Sarjana (S1),Bekerja,1
1,Wajah Jurnalis Dibalut Perban Saat Melaporkan ...,UNKNOWN,0,0,0,0,0,0,0,0,...,Tionghoa,Katolik,yes,no,F,21,Jakarta,Sekolah Menengah Atas (SMA),Pelajar/Mahasiswa,3
2,Elektabilitas Paslon 02 sebentar lagi terjun b...,Disabilitas,0,0,1,0,0,0,0,0,...,Minang,Islam,yes,no,F,27,Padang,Sarjana (S1),Bekerja,1
3,Elektabilitas Paslon 02 sebentar lagi terjun b...,Disabilitas,0,0,1,0,0,0,0,0,...,Tionghoa,Katolik,yes,no,F,21,Jakarta,Sekolah Menengah Atas (SMA),Pelajar/Mahasiswa,3
4,Gini aja deh @KPU_ID usul aja nih. Gimana kalo...,Disabilitas,0,1,0,0,0,1,0,0,...,Minang,Islam,yes,no,F,27,Padang,Sarjana (S1),Bekerja,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51965,@pippsstudy abis packing nnt ingfokan cowo kri...,Kristen,0,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51966,Akun WhatsApp Pj Bupati Tegal Agustyarsah,UNKNOWN,0,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51967,Buldoser Israel Menabrak Pengungsi Pasien Ruma...,"Jewish, Rohingya",0,0,1,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51968,Perayaan Chinese New Year tahun ini ya akan ma...,Tionghoa,0,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2
51969,KNRP #GazaUnderAttack BREAKING NEWS Jumlah Kor...,Jewish,0,0,0,0,0,0,0,0,...,Batak,Kristen,no,no,F,39,Depok,Magister (S2),Bekerja,2

In [18]:
for col in df.columns:
    print(f"\n{'=' * 50}")
    print(f"Kolom: {col}")
    print(df[col].value_counts(dropna=False))

==================================================
Kolom: text
text
Para Pemuda Tiongkok RRC Akan Membanjiri Posisi ASN di Indonesia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              64
Seorang Pria Slovenia di Jerman Dipukuli Karena Dikira Membawa Bendera Rusia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  62
Kasmojo, Dosen Pembimbing Skripsi Jokowi di UGM Jadi Buron                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    62

In [19]:
# df["gender"] = df["gender"].str.strip()
temp = df.columns.drop("text").to_list()
for col in temp:
    print(f"\nKolom: {col}")
    print(df[col].unique())

Kolom: topic
<ArrowStringArray>
[                          'UNKNOWN',                       'Disabilitas',
                          'Tionghoa',                           'Kristen',
                 'Kristen, Tionghoa',                            'Jewish',
                   'Kristen, Jewish',             'Rohingya, Disabilitas',
                  'Tionghoa, Jewish',           'Syiah, Tionghoa, Jewish',
                'Tionghoa, Rohingya',             'Tionghoa, Disabilitas',
                             'Syiah',                     'Syiah, Jewish',
                  'Jewish, Rohingya',               'Jewish, Disabilitas',
                            'LGBTQ+',                    'LGBTQ+, Jewish',
                          'Rohingya',                'Syiah, Disabilitas',
                  'LGBTQ+, Tionghoa',     'Tionghoa, Jewish, Disabilitas',
              'Kristen, Disabilitas',         'Kristen, Jewish, Rohingya',
      'Kristen, Jewish, Disabilitas',                   'Kristen, LGBTQ+',
                         'Ahmadiyah',         'Kristen, Tionghoa, Jewish',
                  'Syiah, Ahmadiyah',               'LGBTQ+, Disabilitas',
        'Syiah, Jewish, Disabilitas',                'Ahmadiyah, Kristen',
            'Syiah, Kristen, Jewish',      'Syiah, Rohingya, Disabilitas',
           'Syiah, Jewish, Rohingya',             'Syiah, LGBTQ+, Jewish',
        'Ahmadiyah, Kristen, Jewish',        'Tionghoa, Jewish, Rohingya',
                   'Syiah, Tionghoa',                 'Kristen, Rohingya',
          'Syiah, Ahmadiyah, Jewish',     'Jewish, Rohingya, Disabilitas',
                   'Syiah, Rohingya',                    'Syiah, Kristen',
                  'LGBTQ+, Rohingya',               'Ahmadiyah, Tionghoa',
                     'Syiah, LGBTQ+', 'Kristen, LGBTQ+, Jewish, Rohingya',
      'Kristen, LGBTQ+, Disabilitas',       'LGBTQ+, Jewish, Disabilitas']
Length: 50, dtype: str

Kolom: is_noise_or_spam_text
[0 1]

Kolom: toxicity
[0 1]

Kolom: polarized
[0 1]

Kolom: profanity_obscenity
[0 1]

Kolom: threat_incitement_to_violence
[0 1]

Kolom: insults
[0 1]

Kolom: identity_attack
[0 1]

Kolom: sexually_explicit
[0 1]

Kolom: key
<ArrowStringArray>
[          '1-1_['7', '15']',          '1-10_['7', '15']',
   '1-100_['7', '15', '32']',  '1-1000_['7', '15', '32']',
       '1-1001_['10', '18']', '1-1003_['10', '18', '32']',
       '1-1004_['10', '18']',       '1-1005_['10', '18']',
 '1-1006_['10', '18', '32']',       '1-1007_['10', '18']',
 ...
               '4-99_['19']',              '4-990_['19']',
              '4-991_['19']',              '4-992_['19']',
              '4-993_['19']',              '4-994_['19']',
              '4-995_['19']',              '4-996_['19']',
              '4-998_['19']',              '4-999_['19']']
Length: 26341, dtype: str

Kolom: cleaned_text
<ArrowStringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Wajah jurnalis dibalut perban saat melaporkan kondisi di Gaza 2023',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Elektabilitas pasangan calon 02 sebentar lagi terjun bebas gara-gara Gemoy, joget, susu gratis, makan gratis, politik dinasti, cacat hukum, ijazah, dan tidak hadir',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Gini aja deh @KPU_ID, usul aja nih. Gimana kalau misalnya tidak usah ada debat kalau nggak boleh dikritik? Diubah jadi lomba joget siapa yang paling gendut sempoyongan 😂🤦👎 Menarik nggak? Atur lah, kalian kan penguasa.. 😁',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Relawan Tionghoa Kalbar yang di Jakarta mendeklarasikan dukungan kepada Ganjar Pranowo. Nama terkait: Mario Dandy, Bu D, Megumi, Putri Ariani, Mamat. Cilacap. Mahkamah Konstitusi.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'Kristen, Hindu, Islam dapat perlakuan istimewa dari Pak Anies Ncep, ketar-ketir',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Paus Fransiskus memulai kunjungan sederhana ke umat Katolik di Mongolia yang beragama Buddha',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'Masyarakat Kristen, Hindu, Buddha, dan etnis Tionghoa di Jawa Timur berharap Prabowo memenangkan Pilpres 2024. dekade08',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'Cina mengirimkan satelit penginderaan jauh baru ke orbit yang direncanakan #MataDunia #technology #china #Aerospace #orbit #sunak #Hindu #newdelhi #india',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'Ganjar-Mahfud adalah wajah toleransi di Indonesia; 57,7% pemilih dari agama Kristen, Hindu, Buddha, Katolik, dan Kong Hu Cu menyatakan dukungannya untuk Ganjar Pranowo. Apalagi Ganjar sukses membawa Jateng jadi daerah toleran; 5 dari 10 kota toleran ada di Jateng #GanjarMahfud2024',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Pendeta Hindu India ini ingin ke Israel untuk memerangi Hamas, idenya kok familiar?',
 ...